config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/terms', to:'static_pages#terms'
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :users, only: [:index, :show] do
    member do
      get :following, :followers, :likes
    end
  end
  get '/picture_edit', to:'users#picture_edit'
  post 'users/:id/picture_update', to:'users#picture_update'
  post '/picture_delete', to:'users#picture_delete'
  resources :microposts do
    resources :comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :notifications, only: :index
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :active_notifications, class_name: 'Notification',
                                  foreign_key: 'visitor_id',
                                  dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification',
                                   foreign_key: 'visited_id',
                                   dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :likes
  has_many :likeposts, through: :likes, source: :micropost
  has_many :comments
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  validates :user_name, presence: true, length: { maximum: 50 }, uniqueness: true
  validates :self_introduction, length: { maximum: 500 }
  validates :phone, length: { maximum: 13 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, length: { maximum: 255 },format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.name
      user.user_name = auth.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end
  
  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end
  
  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end
  
  def like(micropost)
    likes.find_or_create_by(micropost_id: micropost.id)
  end

  def unlike(micropost)
    like = likes.find_by(micropost_id: micropost.id)
    like.destroy if like
  end

  def likepost?(micropost)
    self.likeposts.include?(micropost)
  end
  
  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",
        current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
  
  private
    
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:image_name, "最大データサイズは5MBです。")
      end
    end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
  
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end
  
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:index, :picture_edit,
    :picture_update, :picture_delete, :following, :followers, :likes]
  before_action :correct_user, only: [:picture_update, :picture_delete]
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts
  end
  
  def picture_edit
    @user = User.find(params[:id])
  end
  
  def picture_update
    @user = User.find(params[:id])
    
    if params[:image]
      @user.image_name = "#{@user.id}.jpg"
      image = params[:image]
      File.binwrite("public/user_images/#{@user.image_name}",image.read)
    end
    
    if @user.save
      flash[:notice] = "ユーザー画像を更新しました。"
      redirect_to @user
    else
      @feed_items = []
      render 'users/picture_update'
    end
  end
  
  def picture_delete
    @user = User.find(params[:id])
    @user.image_name = "default_image.jpg"
    @user.save
    flash[:notice] = "ユーザー画像を削除しました。"
    redirect_to @user
  end
  
  def following
    @title = "フォロー"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "フォロワー"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end
  
  def likes
    @title = "お気に入りの投稿"
    @user = User.find(params[:id])
    @likeposts = @user.likeposts.page(params[:page])
    @comment = Comment.new
    render 'show_like'
  end
  
  private
  
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end
    
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
  
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォローする", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user == @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "フォロー中(フォローを解除)", class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= link_to user do %>
    <img class="user_image" src="<%= "/user_images/#{user.image_name}" %>">
  <% end %>
  <%= link_to user.user_name, user %>
</li>

app/views/users/index.html.erb
<% provide(:title, 'ユーザー') %>
<div class="row">
	<div class="col-md-8">
		<h1>ユーザー</h1>
		<%= will_paginate %>
		<ul class="users">
		  <%= render @users %>
		</ul>
		<%= will_paginate %>
	</div>
	<aside class="col-md-4">
		<section class="user_info">
			<%= render 'shared/user_info' %>
		</section>
		<section class="stats">
			<%= render 'shared/stats' %>
		</section>
	</aside>
</div>

app/views/users/picture_edit.html.erb
<% provide(:title, 'ユーザー画像の更新') %>
<%= form_tag("/users/#{@user.id}/picture_update", {multipart: true}) do %>
  <div class="form users-form">
    <img class="user_image" src="<%= "/user_images/#{@user.image_name}" %>">
    <div class="picture">
      <p>画像</p>
      <input name="image" type="file">
      <input class="btn btn-primary" type="submit" value="プロフィール画像を変更">
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.user_name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <% if @user == current_user %> 
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h4 class="modal-title mx-auto" id="exampleModalLabel">プロフィール写真を変更</h4>
              </div>
              <div class="modal-body">
                <span class="link-font"><%= link_to "写真をアップロード", picture_edit_path(id: @user.id) %></span>
              </div>
              <div class="modal-body">
                <span class="denger-link"><%= link_to "現在の写真を削除", picture_delete_path(id: @user.id), method: "post" %></span>
              </div>
              <div class="modal-body-b">
                <span data-dismiss="modal">キャンセル</span>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <h1>
        <img class="user_image link-font" data-toggle="modal" data-target="#myModal"
          src="<%= "/user_images/#{@user.image_name}" %>">
        <%= @user.user_name %>
      </h1>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
    <%= render 'follow_form' if user_signed_in? %>
    <p><%= @user.self_introduction %></p>
  </aside>
  <div class="col-md-4">
    <div class="user_info_box">
      <p><%= link_to("お気に入りの投稿", likes_user_path ) %></p>
      <% if current_user == @user %>
        <p><%= link_to("プロフィール編集", edit_user_registration_path ) %></p>
        <p><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></p>
        <p>
          <%= link_to "アカウント削除", registration_path(@user),
            data: { confirm: "本当によろしいですか?" }, method: :delete %>
        </p>
      <% end %>
    </div>
  </div>
</div>
<div class="row">
  <div class="microposts-box">
    <h3>投稿 (<%= @user.microposts.count %>)</h3>
    <% if @user.microposts.any? %>
      <div class="pictures-wrapper">
        <%= render 'shared/micropost_modal' %>
        <% @microposts.each do |micropost| %>  
          <% if micropost.picture? %>
            <img class="pictures link-font" data-toggle="modal" data-target="#Modal-<%= micropost.id %>" src="<%= micropost.picture.url %>">
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= render 'shared/user_info' %>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>

app/views/users/show_like.html.erb
<% provide(:title, @title) %>
<div class="row">
	<aside class="col-md-4">
		<section class="user_info">
			<%= render 'shared/user_info' %>
		</section>
		<section class="stats">
			<%= render 'shared/stats' %>
		</section>
	</aside>
	<div class="col-md-8">
		<h3><%= @title %>(<%= @user.likeposts.count %>)</h3>
		<%= render 'shared/likepost' %>
	</div>
</div>