config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/terms', to:'static_pages#terms'
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :users, only: [:index, :show] do
    member do
      get :following, :followers, :likes
    end
  end
  get '/picture_edit', to:'users#picture_edit'
  post 'users/:id/picture_update', to:'users#picture_update'
  post '/picture_delete', to:'users#picture_delete'
  resources :microposts do
    resources :comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :notifications, only: :index
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= pluralize(object.errors.count, "つのエラーがあります") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_likepost.html.erb
<% if @likeposts.any? %>
	<ol class="microposts">
		<%= render @likeposts %>
	</ol>
	<%= will_paginate @likeposts %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "投稿文を入力してください..." %>
  </div>
  <%= f.submit "投稿", class: "btn btn-primary" %>
  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/png' %>
  </span>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('最大ファイルサイズは5MBです。サイズが小さい画像を選択してください。');
    }
  });
</script>

app/views/shared/_micropost_modal.html.erb
<% @microposts.each do |micropost| %>
	<div class="modal fade" id="Modal-<%= micropost.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	  <div class="modal-dialog modal-dialog-centered" role="document">
	    <div class="modal-content">
	      <div class="modal-body">
	        <img class="modal-picture" src="<%= micropost.picture.url %>">
	      	<div id="like_form">
					  <% if current_user.likepost?(micropost) %>
					    <%= form_for(current_user.likes.find_by(micropost_id: micropost.id), html: { method: :delete }) do |f| %>
					      <%= hidden_field_tag :micropost_id, micropost.id %>
					      <%= button_tag :type => "submit", class: "btn-like-unlike" do %>
								  <span class="fa fa-heart like-btn-unlike"></span>
								  <%= Like.where(micropost_id: micropost.id).count %>
								<% end %>
					    <% end %>
					  <% else %>
					    <%= form_for(current_user.likes.build) do |f| %>
					      <%= hidden_field_tag :micropost_id, micropost.id %>
					      <%= button_tag :type => "submit", class: "btn-like-unlike" do %>
								  <span class="fa fa-heart like-btn"></span>
								  <%= Like.where(micropost_id: micropost.id).count %>
								<% end %>
					    <% end %>
					  <% end %>
					</div>
	      </div>
	      <% if micropost.comments.any? %>
	        <div class="modal-body">
	          <% micropost.comments.each do |comment| %>
	            <p>
	              <%= link_to comment.user.user_name, user_path(comment.user.id) %>  
	              <%= comment.content %>
	            </p>
	          <% end %>
	        </div>
	      <% end %>
	      <div class="modal-body">
	      	<span><%= link_to "詳細", micropost_path(micropost.id) %></span>　
	      </div>
	      <div class="modal-body-b">　　
	        <span data-dismiss="modal">閉じる　　　</span>
	      </div>
	    </div>
	  </div>
	</div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    フォロー
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    フォロワー
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to current_user do %>
  <img class="user_image" src="<%= "/user_images/#{current_user.image_name}" %>">
<% end %>
<h1><%= current_user.user_name %></h1>
<span><%= link_to "プロフィール", current_user %></span>
<span><b>投稿数:</b> <%= current_user.microposts.count %></span>