config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/terms', to:'static_pages#terms'
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks'}
  resources :users, only: [:index, :show] do
    member do
      get :following, :followers, :likes
    end
  end
  get '/picture_edit', to:'users#picture_edit'
  post 'users/:id/picture_update', to:'users#picture_update'
  post '/picture_delete', to:'users#picture_delete'
  resources :microposts do
    resources :comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :notifications, only: :index
end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= bootstrap_alert(key) %>">
    <strong>
      <%= value %>
    </strong>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav class="center">
    <a href="/microposts/new" class="btn-gradient-simple">投稿</a>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Instagram", root_path, id: "logo" %>
    <% if user_signed_in? %>
      <%= search_form_for @search do |f| %>
        <%= f.search_field :content_cont, class: 'search-form', placeholder: 'キーワードを入力...' %>
        <%= f.submit "検索", class: 'search-form-submit' %>
      <% end %>
    <% end %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ホーム", root_path %></li>
        <% if user_signed_in? %>
          <li class = "notification">
            <%= link_to "通知", notifications_path %>
            <% if unchecked_notifications.any? %>
              <i class="fa fa-circle notification-circle"></i>
            <% end %>
          </li>
          <li><%= link_to current_user.user_name, current_user %></li>
        <% else %>
          <li><%= link_to "ログイン", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'layouts/flashes' %>
      <%= yield %>
      <% if user_signed_in? %>
        <%= render 'layouts/footer' %>
      <% end %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>